# Generated by Django 4.1.3 on 2022-11-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_cover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"permissions": [("special_status", "Can read all books")]},
        ),
    ]
